services:
  pikselite:
    build: .
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/root/.Xauthority
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ~/.Xauthority:/root/.Xauthority:ro
    command: "./pikselite"
    stdin_open: true
    tty: true
