name: Check Windows Compilation
run-name: check-windows-compilation

on:
    push:
        branches:
            - main
            - dev
            - ci_cd
    pull_request:
        branches:
            - main
            - dev
            - ci_cd
permissions:
    contents: read

jobs:
    check_windows_compilation:
        name: Check Windows Compilation
        runs-on: self-hosted
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3
              with:
                    fetch-depth: 0

            - name: Check Windows Compilation
              shell: cmd
              run: |
                echo "Checking Windows compilation..."
                REM Run build.bat at the root of the repository and check for errors
                call build.bat
                if errorlevel 1 (
                    echo "Windows compilation failed with error code %ERRORLEVEL%"
                    exit /b %ERRORLEVEL%
                ) else (
                    echo "Windows compilation succeeded!"
                )
