name: Check Windows Compilation
run-name: check-windows-compilation
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]

    env:
      BUILD_DIR: build
      VCPKG_ROOT: ${{ github.workspace }}\vcpkg
      VCPKG_DEFAULT_TRIPLET: x64-windows
      VCPKG_OVERLAY_PORTS: ${{ github.workspace }}\external\overlay-ports
      VCPKG_CACHE_KEY: windows-vcpkg-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup vcpkg
      shell: cmd
      run: |
        if not exist "%VCPKG_ROOT%" (
          git clone https://github.com/microsoft/vcpkg "%VCPKG_ROOT%"
          call "%VCPKG_ROOT%\bootstrap-vcpkg.bat"
        )

    - name: Build Engine
      shell: cmd
      run: |
        build.bat Cache