name: Check Windows Compilation
run-name: check-windows-compilation
on:
  push:
  # pull_request:

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]

    env:
      BUILD_DIR: build
      VCPKG_ROOT: ${{ github.workspace }}\vcpkg
      VCPKG_DEFAULT_TRIPLET: x64-windows
      VCPKG_OVERLAY_PORTS: ${{ github.workspace }}\external\overlay-ports
      VCPKG_CACHE_KEY: "windows-vcpkg-v1"
      VCPKG_SETUP_CACHE_KEY: "windows-vcpkg-setup-v1"
      CI: true

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Restore vcpkg setup from cache
      shell: cmd
      run: |
        set "CACHE_DIR=%LOCALAPPDATA%\temp\vcpkg-cache"
        set "VCPKG_SETUP_ZIP=%CACHE_DIR%\%VCPKG_SETUP_CACHE_KEY%.zip"
        if exist "%VCPKG_SETUP_ZIP%" (
          echo === Restoring vcpkg setup from cache ===
          if exist "%VCPKG_ROOT%" rmdir /s /q "%VCPKG_ROOT%"
          powershell -Command "Expand-Archive -Path '%VCPKG_SETUP_ZIP%' -DestinationPath '%VCPKG_ROOT%' -Force"
          echo === Vcpkg setup restored from cache ===
        ) else (
          echo === No cached vcpkg setup found ===
        )

    - name: Setup vcpkg
      shell: cmd
      run: |
        if not exist "%VCPKG_ROOT%" (
          git clone https://github.com/microsoft/vcpkg "%VCPKG_ROOT%"
          call "%VCPKG_ROOT%\bootstrap-vcpkg.bat"
        )

    - name: Build Engine
      shell: cmd
      run: |
        build.bat Cache

  test:
    runs-on: [self-hosted, Windows, X64]
    needs: build

    env:
      BUILD_DIR: build
      VCPKG_ROOT: ${{ github.workspace }}\vcpkg
      VCPKG_DEFAULT_TRIPLET: x64-windows
      VCPKG_OVERLAY_PORTS: ${{ github.workspace }}\external\overlay-ports
      VCPKG_CACHE_KEY: "windows-vcpkg-v1"
      VCPKG_SETUP_CACHE_KEY: "windows-vcpkg-setup-v1"
      CI: true

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Restore vcpkg setup from cache
      shell: cmd
      run: |
        set "CACHE_DIR=%LOCALAPPDATA%\temp\vcpkg-cache"
        set "VCPKG_SETUP_ZIP=%CACHE_DIR%\%VCPKG_SETUP_CACHE_KEY%.zip"
        if exist "%VCPKG_SETUP_ZIP%" (
          echo === Restoring vcpkg setup from cache ===
          if exist "%VCPKG_ROOT%" rmdir /s /q "%VCPKG_ROOT%"
          powershell -Command "Expand-Archive -Path '%VCPKG_SETUP_ZIP%' -DestinationPath '%VCPKG_ROOT%' -Force"
          echo === Vcpkg setup restored from cache ===
        ) else (
          echo === No cached vcpkg setup found ===
        )


    - name: Setup vcpkg
      shell: cmd
      run: |
        if not exist "%VCPKG_ROOT%" (
          git clone https://github.com/microsoft/vcpkg "%VCPKG_ROOT%"
          call "%VCPKG_ROOT%\bootstrap-vcpkg.bat"
        )

    - name: Build Debug
      shell: cmd
      run: |
        build.bat Debug

    - name: Run Tests
      shell: cmd
      run: |
        call "%ProgramFiles(x86)%\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x64
        cd build
        ctest --output-on-failure