name: Static Checks
run-name: ${{github.event_name}}-${{github.actor}}-${{github.run_id}}

on:
    push:
        branches-ignore:
            - "ga-ignore-*"
    pull_request:
        branches-ignore:
            - "ga-ignore-*"


jobs:
    static_checks:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                    sudo apt-get update
                    sudo apt-get install -y \
                        clang-format \
                        clang-tidy \
                        cppcheck \
                        cmake \
                        build-essential \
                        ninja-build \
                        gcc \
                        g++ \
                        pkg-config

            - name: Install OpenGL dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y \
                libgl1-mesa-dev \
                libglu1-mesa-dev \
                freeglut3-dev \
                libx11-dev \
                libxrandr-dev \
                libxi-dev \
                libxinerama-dev \
                libxcursor-dev

            - name: Setup vcpkg
              run: |
                git clone https://github.com/microsoft/vcpkg
                ./vcpkg/bootstrap-vcpkg.sh

            - name: Generate compile_commands.json
              run: |
                cmake -S . -B build \
                -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake \
                -DVCPKG_TARGET_TRIPLET=x64-linux \
                -DCMAKE_BUILD_TYPE=Debug \
                -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

            - name: Check code formatting
              run: |
                    FILES=$(find . \( -name "*.cpp" -o -name "*.hpp" -o -name "*.h" \))
                    clang-format --dry-run --Werror $FILES

            - name: Run linting
              run: |
                FILES=$(find . \( -name "*.cpp" -o -name "*.hpp" -o -name "*.h" \))
                clang-tidy $FILES -- -I. -Iinclude

            - name: Run cppcheck
              run: |
                cppcheck \
                --enable=all \
                --inconclusive \
                --std=c++20 \
                --force \
                --quiet \
                --error-exitcode=1 \
                -I include \
                .